
@startuml

package "用户操作" {
  START -> [扫描营业执照/填写企业名信用代码]
  [扫描营业执照/填写企业名信用代码] --> [扫描法人身份证]
  [扫描法人身份证] --> [客户填写主要人员信息]
  [客户填写主要人员信息] --> [按照系统给出的股东姓名扫描身份证]

}

node "后台业务流程" {
  [扫描营业执照/填写企业名信用代码] ..> [营业执照信息入库]

  [扫描法人身份证] ..> [法人信息入库]

  [客户填写主要人员信息] ..> [财务负责人、经办人信息入库]

  [客户填写主要人员信息] ..> [受益人信息入库]

  [客户填写主要人员信息] ..> [法人信息入库]:电话

  [查询股东信息] ..> [按照系统给出的股东姓名扫描身份证]

  [按照系统给出的股东姓名扫描身份证] ..> [股东信息入库]

}

cloud {
  [企业信息供应商]
}


database "Database" {
  folder "营业执照信息" {
	[企业名称]
	[主体类型]
	[企业地址]
	[法人姓名]
	[成立日期]
	[信用代码]
	[登记机关]
  }
  frame "身份信息" {
    [人员类型]
	[姓名]
	[证件号码]
	[证件有效期]
	[出生日期]
	[国籍]
    [电话]
  }
  folder "云端获取企业信息" {
    [注册/成立地区]
    [经营范围]
    [股东姓名]
    [出资比例]
    [受益人姓名]
  }
  folder "其他企业信息" {
    [行业类型]
    [客户类型]
  }
}

[营业执照信息入库] ..> 营业执照信息
[法人信息入库] ..> 身份信息:法人
[财务负责人、经办人信息入库] ..> 身份信息:财务负责人、经办人
[受益人信息入库] ..> 身份信息:受益人
[股东信息入库] ..> 身份信息:股东
[法人姓名] -- [姓名]: 验证
[企业信息供应商] ..> [查询股东信息]:股东姓名、出资比例

@enduml