
@startuml

package "业务流程" {
  package "客户操作" {
    开始 --> [扫描营业执照或填写企业全称]:业务人员确认营业执照法人
    [扫描营业执照或填写企业全称] --> [按法人姓名扫描身份证]
    [按法人姓名扫描身份证] --> [按股东姓名扫描身份证]
    [按股东姓名扫描身份证] --> [客户填写主要人员信息]
  }
  [客户填写主要人员信息] --> [业务人员填写信息]
  [业务人员填写信息] ..> [核实企业司法经营信息]:可选

}

note left of [按股东姓名扫描身份证]
根据云端查询股东姓名、
出资比例，根据业务逻辑
确定股东并扫描身份证
end note

note left of [客户填写主要人员信息]
客户需要填写法人手机
财务负责人、经办人身份
信息、受益人身份信息
（支持扫描身份证）
end note

node "后台业务流程" {
  [按法人姓名扫描身份证] ....> [法人身份信息入库]
  [按股东姓名扫描身份证] ....> [股东身份信息入库]
  [客户填写主要人员信息] ....> [财务负责人、经办人信息入库]
  [客户填写主要人员信息] ....> [受益人信息入库]
  [客户填写主要人员信息] ....> [法人身份信息入库]:电话
  [业务人员填写信息] ....> [其他企业信息入库]


  [法人身份信息入库] ....> 身份信息:法人身份信息
  [获取企业基本信息] ....> 企业信息
  [核实企业司法经营信息] <.... [企业司法、经营信息]
  [股东身份信息入库] ....> 身份信息:股东身份信息
  [财务负责人、经办人信息入库] ....> 身份信息:财务负责人、经办人
  [受益人信息入库] ....> 身份信息:受益人
  [其他企业信息入库] ....> 其他企业信息

}

cloud {
  [企业信息供应商]
}


database "Database" {
  frame "身份信息" {
    [人员类型]
	[姓名]
	[证件号码]
	[证件有效期]
	[出生日期]
	[国籍]
    [电话]
  }

  folder "企业信息" {
  	[企业名称]
  	[信用代码]
  	[主体类型]
  	[企业地址]
  	[法人姓名]
  	[成立日期]
  	[信用代码]
  	[登记机关]
    [注册/成立地区]
    [经营范围]
    [股东姓名]
    [出资比例]
  }
  folder "其他企业信息" {
    [行业类型]
    [客户类型]
    [销售额]
    [机构类别]
    [居民身份]
    [开户目的]
    [经营国家]
    [企业规模]
    [营业国家]
    [反洗钱确认项目]
  }
  folder "司法经营风险信息" {
    [失信人]
    [被执行人]
    [行政处罚]
    [动产抵押]
    [欠税公告]
  }
}


[扫描营业执照或填写企业全称] ....> [企业信息供应商]:提供企业全称
[企业信息供应商] ....> [获取企业基本信息]
[企业信息供应商] ....> [企业司法、经营信息]
[企业信息供应商] ....> [按法人姓名扫描身份证]:法人姓名
[企业信息供应商] ....> [按股东姓名扫描身份证]:股东姓名
[企业司法、经营信息] <.... 司法经营风险信息

[对接前台系统] <- Database:可设计流水号直接供数
@enduml