#!/bin/sh
# Gaomingjie - 20180527 

# -- envs --

TEMP=/tmp
LOGFILE=$TEMP/SetupSSH_`date +%F-%H-%M-%S`.log

# -- global --

nargs=$#
n=1
logfile=$LOGFILE
platform=`uname -s`




# -- function --

usage()
{
cat <<EOF
$0
Description: 

Usage: 

Examples:

EOF
}

verify_bins()
{
SSH="/usr/bin/ssh"
SCP="/usr/bin/scp"
SSH_KEYGEN="/usr/bin/ssh-keygen"
if [ $platform = "Linux" ]
then
  PING="/bin/ping"
else
  PING="/usr/sbin/ping"
fi
PATH_ERROR=0
if test ! -x $SSH ; then
  echo "ssh not found at $SSH. Please set the variable SSH_PATH to the correct location of ssh and retry."
  PATH_ERROR=1
fi 
if test ! -x $SCP ; then
  echo "scp not found at $SCP. Please set the variable SCP_PATH to the correct location of scp and retry."
  PATH_ERROR=1
fi 
if test ! -x $SSH_KEYGEN ; then
  echo "ssh-keygen not found at $SSH_KEYGEN. Please set the variable SSH_KEYGEN_PATH to the correct location of ssh-keygen and retry."
  PATH_ERROR=1
fi 
if test ! -x $PING ; then
  echo "ping not found at $PING. Please set the variable PING_PATH to the correct location of ping and retry."
  PATH_ERROR=1
fi 
if [ $PATH_ERROR = 1 ]; then
  echo "ERROR: one or more of the required binaries not found, exiting"
  exit 1
fi
}

verify_params()
{
if test -z "$hosts"; then
  if test -n "$host_file" && test -f "$host_file"; then
    hosts=`awk '$1 !~ /^#/ { str = str " " $1 } END { print str }' $host_file` 
  elif ! test -f "$host_file"; then
    echo "Please specify a valid and existing hosts file."
  fi
fi

if  test -z "$hosts" || test -z $user
then
echo "Either user name or host information is missing"
usage
exit 1
fi

if [ -d $logfile ]; then
  echo $logfile is a directory, setting logfile to $logfile/ssh.log
  logfile=$logfile/ssh.log
fi

echo The output of this script is also logged into $logfile | tee -a $logfile

if [ `echo $?` != 0 ]; then
  echo Error writing to the logfile $logfile, Exiting
  exit 1
fi

echo Hosts are $hosts | tee -a $logfile
echo User is  $user | tee -a $logfile

}

verify_os()
{
  case "$platform" in
    "SunOS")  os=solaris;;
    "Linux")  os=linux;;
    "HP-UX")  os=hpunix;;
      "AIX")  os=aix;;
          *)  echo "Sorry, $platform is not currently supported." | tee -a $LOGFILE
              exit 1;;
  esac
  echo "Platform: $platform " | tee -a $LOGFILE
}

# -- entry --

while [ $n -le $nargs ]; do
  par=$1

  if [ $par = "-help" ]; then
    usage
    exit
  fi

  if [ $par = "-hosts" ] 
  then
     hosts=$2
     shift 1
     n=`expr $n + 1`
  fi
   if [ $par = "-hostfile" ] 
  then
     host_file=$2
     shift 1
     n=`expr $n + 1`
   fi
  if [ $par = "-user" ] 
  then
     user=$2
     shift 1
     n=`expr $n + 1`
   fi
  if [ $par = "-logfile" ] 
  then
     logfile=$2
     shift 1
     n=`expr $n + 1`
  fi
  # shift if no match
  shift 1
  n=`expr $n + 1`
done

verify_params
verify_os
verify_bins








